### ISSUE TITLE
Case syntax error on linux

### ISSUE THREAD

**Issue by tjoyal** [flyingmachine/whoops_logger#1]
I'm not that good in ruby but it dosent seems this case syntax works on at least linux

whoops_logger / lib / whoops_logger / configuration.rb : line 82 to 86

SyntaxError (/home/thierry/.rvm/gems/ruby-1.9.2-p180@test/gems/whoops_logger-0.1.2/lib/whoops_logger/configuration.rb:87: syntax error, unexpected ':', expecting keyword_then or ',' or ';' or '\n'
      when Hash: set_with_hash(config)
                ^
/home/thierry/.rvm/gems/ruby-1.9.2-p180@test/gems/whoops_logger-0.1.2/lib/whoops_logger/configuration.rb:88: syntax error, unexpected keyword_when, expecting keyword_end
      when IO: set_with_io(config)
          ^
/home/thierry/.rvm/gems/ruby-1.9.2-p180@test/gems/whoops_logger-0.1.2/lib/whoops_logger/configuration.rb:89: syntax error, unexpected keyword_when, expecting keyword_end
      when String: set_with_string(config)

Here an extra "rails c" from my setup :

ruby-1.9.2-p180 :018 > case 'a'
ruby-1.9.2-p180 :019?>   when 'a':
ruby-1.9.2-p180 :020 >     puts 'test'
ruby-1.9.2-p180 :021?>   else
ruby-1.9.2-p180 :022 >     puts 'default'
ruby-1.9.2-p180 :023?>   end
SyntaxError: (irb):19: syntax error, unexpected ':', expecting keyword_then or ',' or ';' or '\n'
(irb):21: syntax error, unexpected keyword_else, expecting $end
        from /home/thierry/.rvm/gems/ruby-1.9.2-p180@test/gems/railties-3.0.7/lib/rails/commands/console.rb:44:in `start'
        from /home/thierry/.rvm/gems/ruby-1.9.2-p180@test/gems/railties-3.0.7/lib/rails/commands/console.rb:8:in`start'
        from /home/thierry/.rvm/gems/ruby-1.9.2-p180@test/gems/railties-3.0.7/lib/rails/commands.rb:23:in `<top (required)>'
        from script/rails:6:in`require'
        from script/rails:6:in `<main>'

**Comment by flyingmachine** [comment]
you're right -that doesn't work  in ruby 1.9.2 . I'll have to fix. Thank you.

**Comment by maxschulze** [comment]
This works on the latest master branch, can be closed :-)

**Comment by flyingmachine** [comment]
heh thanks :) tjoyal fixed.
